// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "bufio"
	_ "encoding/json"
	_ "fmt"
	_ "github.com/mitchellh/go-homedir"
	_ "github.com/spf13/cobra"
	_ "github.com/spf13/pflag"
	_ "github.com/spf13/viper"
	_ "gopkg.in/resty.v1"
	_ "io/ioutil"
	_ "os"
	_ "path/filepath"
	_ "regexp"
	_ "strings"
	_ "time"
)
